name: im_animations
description: A growing collection of cool, elegant, efficient and performance-optimized animation widgets.
version: 0.1.2
homepage: https://twitter.com/imujtaba8488
repository: https://github.com/imujtaba8488/im_animations.git
issue_tracker: https://github.com/imujtaba8488/im_animations/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/stamp.jpeg
    - assets/avatars/